/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_Descuentos extends javax.swing.JFrame {
    public TiendaInstrumento musicGo=new TiendaInstrumento();
    /**
     * Creates new form Descuentos
     */
    public GUI_Descuentos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMenuPrincipal = new javax.swing.JButton();
        lblDescuento10 = new javax.swing.JLabel();
        lblDescuento15 = new javax.swing.JLabel();
        lblDescuento25 = new javax.swing.JLabel();
        lblDescuento50 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblGuitarraConDescuento = new javax.swing.JLabel();
        lblFlautaConDescuento = new javax.swing.JLabel();
        lblBateriaConDescuneto = new javax.swing.JLabel();
        lblTecladoConDescuento = new javax.swing.JLabel();
        btnComprarFlautaconDesceunto10 = new javax.swing.JButton();
        btnComprarGuitarraConDescuento15 = new javax.swing.JButton();
        btnComprarBateriaConDescuento25 = new javax.swing.JButton();
        btnComprarTecladoConDescuento50 = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuPrincipal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMenuPrincipal.setText("Atrás");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 90, 40));

        lblDescuento10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Desceuntos/desceunto10.png"))); // NOI18N
        getContentPane().add(lblDescuento10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblDescuento15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Desceuntos/desceunto15.png"))); // NOI18N
        getContentPane().add(lblDescuento15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        lblDescuento25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Desceuntos/descuento25.png"))); // NOI18N
        getContentPane().add(lblDescuento25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        lblDescuento50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Desceuntos/desceunto50.png"))); // NOI18N
        getContentPane().add(lblDescuento50, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setText("¡NUESTROS PRODUCTOS CON DESCUENTOS!");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        lblGuitarraConDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GuitarraAcustica/Guitarra-Acustica1.png"))); // NOI18N
        getContentPane().add(lblGuitarraConDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 120, -1));

        lblFlautaConDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flautas/flauta2.png"))); // NOI18N
        getContentPane().add(lblFlautaConDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        lblBateriaConDescuneto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Bateria/bateria4.png"))); // NOI18N
        getContentPane().add(lblBateriaConDescuneto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        lblTecladoConDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Teclados/teclado4.png"))); // NOI18N
        getContentPane().add(lblTecladoConDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        btnComprarFlautaconDesceunto10.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarFlautaconDesceunto10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarFlautaconDesceunto10.setText("Comprar");
        btnComprarFlautaconDesceunto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarFlautaconDesceunto10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarFlautaconDesceunto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        btnComprarGuitarraConDescuento15.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarGuitarraConDescuento15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarGuitarraConDescuento15.setText("Comprar");
        btnComprarGuitarraConDescuento15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarGuitarraConDescuento15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarGuitarraConDescuento15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        btnComprarBateriaConDescuento25.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarBateriaConDescuento25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarBateriaConDescuento25.setText("Comprar");
        btnComprarBateriaConDescuento25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarBateriaConDescuento25ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarBateriaConDescuento25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        btnComprarTecladoConDescuento50.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarTecladoConDescuento50.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarTecladoConDescuento50.setText("Comprar");
        btnComprarTecladoConDescuento50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarTecladoConDescuento50ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarTecladoConDescuento50, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        lblInfo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblInfo.setText("Haz click en \"comprar\" para más información!");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 400, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/FondoNuevosProductos.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 468));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        GUI_MenuPrincipal  menuPrincipal = new GUI_MenuPrincipal();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnComprarFlautaconDesceunto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarFlautaconDesceunto10ActionPerformed
        // TODO add your handling code here:
        Instrumento.nomInstrumento = "Flauta";
        Instrumento miFlautaconDescuento10 = new Directo("Plata", "Negro", 0.6, 0.11, "YAMAHA");
        Instrumento.precioInst = miFlautaconDescuento10.calcularPrecio(Instrumento.nomInstrumento);
        musicGo.setInstrumentos(miFlautaconDescuento10);
        Instrumento.descuentoEXTRA = 0.10;
        Instrumento.descripcionInstr = miFlautaconDescuento10.toString();
        
        GUI_Compra compra  = new GUI_Compra();
        compra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComprarFlautaconDesceunto10ActionPerformed

    private void btnComprarGuitarraConDescuento15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarGuitarraConDescuento15ActionPerformed
        // TODO add your handling code here:
        Instrumento.nomInstrumento = "Guitarra Acústica";
        Instrumento miGuitarraconDescuento15 = new Punteo("Caoba", "Rojo", 1.4, 1.75, "VINTAGE");
        Instrumento.precioInst = miGuitarraconDescuento15.calcularPrecio(Instrumento.nomInstrumento);
        musicGo.setInstrumentos(miGuitarraconDescuento15);
        Instrumento.descuentoEXTRA = 0.15;
        Instrumento.descripcionInstr = miGuitarraconDescuento15.toString();
        
        GUI_Compra compra  = new GUI_Compra();
        compra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComprarGuitarraConDescuento15ActionPerformed

    private void btnComprarBateriaConDescuento25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBateriaConDescuento25ActionPerformed
        // TODO add your handling code here:
        Instrumento.nomInstrumento = "Bateria";
        Instrumento miBateriaconDescuento25 = new PercusionMembranofos("Sapele", "Azul", 4, 45, "PREMIER");
        Instrumento.precioInst = miBateriaconDescuento25.calcularPrecio(Instrumento.nomInstrumento);
        musicGo.setInstrumentos(miBateriaconDescuento25);
        Instrumento.descuentoEXTRA = 0.25;
        Instrumento.descripcionInstr = miBateriaconDescuento25.toString();
        
        GUI_Compra compra  = new GUI_Compra();
        compra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComprarBateriaConDescuento25ActionPerformed

    private void btnComprarTecladoConDescuento50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarTecladoConDescuento50ActionPerformed
        // TODO add your handling code here:
        Instrumento.nomInstrumento = "Teclado Eléctrico";
        Instrumento miTecladoconDescuento50 = new Electronicos("Negro",32, 8, "CASIO");
        Instrumento.precioInst = miTecladoconDescuento50.calcularPrecio(Instrumento.nomInstrumento);
        musicGo.setInstrumentos(miTecladoconDescuento50);
        Instrumento.descuentoEXTRA = 0.5;
        Instrumento.descripcionInstr = miTecladoconDescuento50.toString();
        
        GUI_Compra compra  = new GUI_Compra();
        compra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComprarTecladoConDescuento50ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Descuentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Descuentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarBateriaConDescuento25;
    private javax.swing.JButton btnComprarFlautaconDesceunto10;
    private javax.swing.JButton btnComprarGuitarraConDescuento15;
    private javax.swing.JButton btnComprarTecladoConDescuento50;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBateriaConDescuneto;
    private javax.swing.JLabel lblDescuento10;
    private javax.swing.JLabel lblDescuento15;
    private javax.swing.JLabel lblDescuento25;
    private javax.swing.JLabel lblDescuento50;
    private javax.swing.JLabel lblFlautaConDescuento;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGuitarraConDescuento;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTecladoConDescuento;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
