/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_GuitarraAcustica extends javax.swing.JFrame {

    /**
     * Creates new form GuitarraAcustica
     */
    public GUI_GuitarraAcustica() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGuitarraA1 = new javax.swing.JLabel();
        lblGuitarraA2 = new javax.swing.JLabel();
        lblGuitarraA3 = new javax.swing.JLabel();
        lblGuitarraA4 = new javax.swing.JLabel();
        btnAtrasCuerdas = new javax.swing.JButton();
        btnComprarGuitarraA1 = new javax.swing.JButton();
        btnComprarGuitarraA2 = new javax.swing.JButton();
        btnComprarGuitarraA3 = new javax.swing.JButton();
        btnComprarGuitarraA4 = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGuitarraA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GuitarraAcustica/Guitarra-Acustica1.png"))); // NOI18N
        getContentPane().add(lblGuitarraA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        lblGuitarraA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GuitarraAcustica/Guitarra-Acustica2.png"))); // NOI18N
        getContentPane().add(lblGuitarraA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        lblGuitarraA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GuitarraAcustica/Guitarra-Acustica3.png"))); // NOI18N
        getContentPane().add(lblGuitarraA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        lblGuitarraA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GuitarraAcustica/Guitarra-Acustica4.png"))); // NOI18N
        getContentPane().add(lblGuitarraA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        btnAtrasCuerdas.setBackground(new java.awt.Color(255, 255, 255));
        btnAtrasCuerdas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAtrasCuerdas.setText("Atrás");
        btnAtrasCuerdas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCuerdasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasCuerdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 90, 40));

        btnComprarGuitarraA1.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarGuitarraA1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarGuitarraA1.setText("Comprar");
        getContentPane().add(btnComprarGuitarraA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 110, 30));

        btnComprarGuitarraA2.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarGuitarraA2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarGuitarraA2.setText("Comprar");
        getContentPane().add(btnComprarGuitarraA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 110, 30));

        btnComprarGuitarraA3.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarGuitarraA3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarGuitarraA3.setText("Comprar");
        getContentPane().add(btnComprarGuitarraA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 110, 30));

        btnComprarGuitarraA4.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarGuitarraA4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarGuitarraA4.setText("Comprar");
        getContentPane().add(btnComprarGuitarraA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 110, 30));

        lblInfo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblInfo.setText("Haz click en \"comprar\" para más información!");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 400, 40));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("GUITARRAS ACÚSTICAS");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/FondoPrincipal.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasCuerdasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCuerdasActionPerformed
        // TODO add your handling code here:
        GUI_Cuerdas menuCuerdas = new GUI_Cuerdas();
        menuCuerdas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasCuerdasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_GuitarraAcustica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_GuitarraAcustica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_GuitarraAcustica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_GuitarraAcustica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_GuitarraAcustica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCuerdas;
    private javax.swing.JButton btnComprarGuitarraA1;
    private javax.swing.JButton btnComprarGuitarraA2;
    private javax.swing.JButton btnComprarGuitarraA3;
    private javax.swing.JButton btnComprarGuitarraA4;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGuitarraA1;
    private javax.swing.JLabel lblGuitarraA2;
    private javax.swing.JLabel lblGuitarraA3;
    private javax.swing.JLabel lblGuitarraA4;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
