/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_Percusion extends javax.swing.JFrame {

    /**
     * Creates new form Percusion
     */
    public GUI_Percusion() {
        initComponents();
        setLocationRelativeTo(null);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuPrincipal = new javax.swing.JButton();
        lblBaterias = new javax.swing.JLabel();
        lblCongas = new javax.swing.JLabel();
        lblBongos = new javax.swing.JLabel();
        btnBaterias = new javax.swing.JButton();
        btnCongas = new javax.swing.JButton();
        btnBongos = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblLogoPrincipalMarca = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuPrincipal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMenuPrincipal.setText("Atrás");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 408, 90, 40));

        lblBaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Bateria/bateria1.png"))); // NOI18N
        getContentPane().add(lblBaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblCongas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Congas/conga1.png"))); // NOI18N
        getContentPane().add(lblCongas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        lblBongos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Bongos/bongos3.png"))); // NOI18N
        getContentPane().add(lblBongos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        btnBaterias.setBackground(new java.awt.Color(255, 255, 255));
        btnBaterias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBaterias.setText("Baterías");
        btnBaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBateriasActionPerformed(evt);
            }
        });
        getContentPane().add(btnBaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 150, 40));

        btnCongas.setBackground(new java.awt.Color(255, 255, 255));
        btnCongas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCongas.setText("Congas");
        btnCongas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCongas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 150, 40));

        btnBongos.setBackground(new java.awt.Color(255, 255, 255));
        btnBongos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBongos.setText("Bongos");
        btnBongos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBongosActionPerformed(evt);
            }
        });
        getContentPane().add(btnBongos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 150, 40));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("¡NUESTROS PRODUCTOS SON!");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 10, 360, -1));

        lblLogoPrincipalMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPrincipalMarca1.png"))); // NOI18N
        getContentPane().add(lblLogoPrincipalMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 170, 50));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/FondoMarcas.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        GUI_Proyecto  menuPrincipal = new GUI_Proyecto();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnBateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBateriasActionPerformed
        // TODO add your handling code here:
        GUI_Bateria baterias = new GUI_Bateria();
        baterias.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBateriasActionPerformed

    private void btnCongasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongasActionPerformed
        // TODO add your handling code here:
        GUI_Congas conga = new GUI_Congas();
        conga.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCongasActionPerformed

    private void btnBongosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBongosActionPerformed
        // TODO add your handling code here:
        GUI_Bongos bongo = new GUI_Bongos();
        bongo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBongosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Percusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Percusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Percusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Percusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Percusion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaterias;
    private javax.swing.JButton btnBongos;
    private javax.swing.JButton btnCongas;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel lblBaterias;
    private javax.swing.JLabel lblBongos;
    private javax.swing.JLabel lblCongas;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoPrincipalMarca;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
