
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_TecladoElectrico extends javax.swing.JFrame {

    
    static String ins;
    /**
     * Creates new form TecladoElectrico
     */
    public GUI_TecladoElectrico() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("Imagenes/LogoIcono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtrasTeclado = new javax.swing.JButton();
        lblTecladoE1 = new javax.swing.JLabel();
        lblTecladoE2 = new javax.swing.JLabel();
        lblTecladoE3 = new javax.swing.JLabel();
        lblTecladoE4 = new javax.swing.JLabel();
        btnTecladoE1 = new javax.swing.JButton();
        btnTecladoE2 = new javax.swing.JButton();
        btnTecladoE3 = new javax.swing.JButton();
        btnTecladoE4 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasTeclado.setBackground(new java.awt.Color(255, 255, 255));
        btnAtrasTeclado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAtrasTeclado.setText("Atrás");
        btnAtrasTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasTecladoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasTeclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 409, 90, 40));

        lblTecladoE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Teclados/teclado1.png"))); // NOI18N
        getContentPane().add(lblTecladoE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        lblTecladoE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Teclados/teclado2.png"))); // NOI18N
        getContentPane().add(lblTecladoE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        lblTecladoE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Teclados/teclado3.png"))); // NOI18N
        getContentPane().add(lblTecladoE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        lblTecladoE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Teclados/teclado4.png"))); // NOI18N
        getContentPane().add(lblTecladoE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        btnTecladoE1.setBackground(new java.awt.Color(255, 255, 255));
        btnTecladoE1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTecladoE1.setText("Comprar");
        btnTecladoE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecladoE1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTecladoE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 30));

        btnTecladoE2.setBackground(new java.awt.Color(255, 255, 255));
        btnTecladoE2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTecladoE2.setText("Comprar");
        btnTecladoE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecladoE2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTecladoE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 110, 30));

        btnTecladoE3.setBackground(new java.awt.Color(255, 255, 255));
        btnTecladoE3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTecladoE3.setText("Comprar");
        btnTecladoE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecladoE3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTecladoE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 110, 30));

        btnTecladoE4.setBackground(new java.awt.Color(255, 255, 255));
        btnTecladoE4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTecladoE4.setText("Comprar");
        btnTecladoE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecladoE4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTecladoE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 110, 30));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("TECLADOS ELÉCTRICOS");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        lblInfo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblInfo.setText("Haz click en \"comprar\" para más información!");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 400, 40));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/FondoDescuentos.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasTecladoActionPerformed
        // TODO add your handling code here:
        GUI_Teclado piano = new GUI_Teclado();
        piano.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasTecladoActionPerformed

    private void btnTecladoE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecladoE1ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesTecladoElectrico OpcionesCompra  = new GUI_OpcionesTecladoElectrico();
        OpcionesCompra.setVisible(true);
        dispose();
        ins = "pianoElectrico1";
    }//GEN-LAST:event_btnTecladoE1ActionPerformed

    private void btnTecladoE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecladoE2ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesTecladoElectrico OpcionesCompra  = new GUI_OpcionesTecladoElectrico();
        OpcionesCompra.setVisible(true);
        dispose();
        ins = "pianoElectrico2";
    }//GEN-LAST:event_btnTecladoE2ActionPerformed

    private void btnTecladoE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecladoE3ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesTecladoElectrico OpcionesCompra  = new GUI_OpcionesTecladoElectrico();
        OpcionesCompra.setVisible(true);
        dispose();
        ins = "pianoElectrico3";
    }//GEN-LAST:event_btnTecladoE3ActionPerformed

    private void btnTecladoE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecladoE4ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesTecladoElectrico OpcionesCompra  = new GUI_OpcionesTecladoElectrico();
        OpcionesCompra.setVisible(true);
        dispose();
        ins = "pianoElectrico4";
    }//GEN-LAST:event_btnTecladoE4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_TecladoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_TecladoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_TecladoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_TecladoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TecladoElectrico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasTeclado;
    private javax.swing.JButton btnTecladoE1;
    private javax.swing.JButton btnTecladoE2;
    private javax.swing.JButton btnTecladoE3;
    private javax.swing.JButton btnTecladoE4;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTecladoE1;
    private javax.swing.JLabel lblTecladoE2;
    private javax.swing.JLabel lblTecladoE3;
    private javax.swing.JLabel lblTecladoE4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
