/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_OpcionesConga extends javax.swing.JFrame {

    /**
     * Creates new form GUI_OpcionesConga
     */
    public GUI_OpcionesConga() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColor = new javax.swing.ButtonGroup();
        buttonGroupMarca = new javax.swing.ButtonGroup();
        buttonGroupMaterial = new javax.swing.ButtonGroup();
        buttonGroupTamaño = new javax.swing.ButtonGroup();
        buttonGroupPeso = new javax.swing.ButtonGroup();
        lblLogoPrincipalMarca = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();
        rbtnAzul = new javax.swing.JRadioButton();
        rbtnRojo = new javax.swing.JRadioButton();
        rbtnCafe = new javax.swing.JRadioButton();
        rbtnNegro = new javax.swing.JRadioButton();
        lblMarca = new javax.swing.JLabel();
        jPanelMarca = new javax.swing.JPanel();
        rbtnStrong = new javax.swing.JRadioButton();
        rbtnLatinPercussion = new javax.swing.JRadioButton();
        rbtnCameMusic = new javax.swing.JRadioButton();
        btnAtrasCuerdas = new javax.swing.JButton();
        lblCOnga = new javax.swing.JLabel();
        jPanelTamaño = new javax.swing.JPanel();
        rbtnTam0762 = new javax.swing.JRadioButton();
        rbtnTam07112 = new javax.swing.JRadioButton();
        lblTamaño = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        jPanelMaterial = new javax.swing.JPanel();
        rbtnMatCaoba = new javax.swing.JRadioButton();
        rbtnMatSapele = new javax.swing.JRadioButton();
        lblCOnga1 = new javax.swing.JLabel();
        lblSonido = new javax.swing.JLabel();
        btnSonido = new javax.swing.JButton();
        jPanelPeso = new javax.swing.JPanel();
        rbtnPeso145 = new javax.swing.JRadioButton();
        rbtnPeso1616 = new javax.swing.JRadioButton();
        lblPeso = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoPrincipalMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPrincipalMarca1.png"))); // NOI18N
        getContentPane().add(lblLogoPrincipalMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 200, 50));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("¡Elige lo que más te guste!");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblColor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblColor.setText("COLOR");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 20));

        jPanelColor.setBackground(new java.awt.Color(204, 255, 204));

        rbtnAzul.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnAzul);
        rbtnAzul.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnAzul.setText("Azul");

        rbtnRojo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnRojo);
        rbtnRojo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnRojo.setText("Rojo");

        rbtnCafe.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnCafe);
        rbtnCafe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnCafe.setText("Café");

        rbtnNegro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnNegro);
        rbtnNegro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnNegro.setText("Negro");

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnAzul)
                    .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbtnNegro)
                        .addComponent(rbtnCafe, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbtnRojo, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnNegro)
                .addGap(18, 18, 18)
                .addComponent(rbtnCafe)
                .addGap(18, 18, 18)
                .addComponent(rbtnRojo)
                .addGap(18, 18, 18)
                .addComponent(rbtnAzul)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 160));

        lblMarca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMarca.setText("MARCA");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, 30));

        jPanelMarca.setBackground(new java.awt.Color(204, 255, 204));

        buttonGroupMarca.add(rbtnStrong);
        rbtnStrong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnStrong.setText("STRONG");

        buttonGroupMarca.add(rbtnLatinPercussion);
        rbtnLatinPercussion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnLatinPercussion.setText("Latin Percussion ");

        buttonGroupMarca.add(rbtnCameMusic);
        rbtnCameMusic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnCameMusic.setSelected(true);
        rbtnCameMusic.setText("CAMEMUSIC ");

        javax.swing.GroupLayout jPanelMarcaLayout = new javax.swing.GroupLayout(jPanelMarca);
        jPanelMarca.setLayout(jPanelMarcaLayout);
        jPanelMarcaLayout.setHorizontalGroup(
            jPanelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMarcaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCameMusic)
                    .addComponent(rbtnLatinPercussion)
                    .addComponent(rbtnStrong))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelMarcaLayout.setVerticalGroup(
            jPanelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnStrong)
                .addGap(18, 18, 18)
                .addComponent(rbtnLatinPercussion)
                .addGap(18, 18, 18)
                .addComponent(rbtnCameMusic)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 120));

        btnAtrasCuerdas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAtrasCuerdas.setText("Atrás");
        btnAtrasCuerdas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCuerdasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasCuerdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 40));

        lblCOnga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Congas/conga4.png"))); // NOI18N
        getContentPane().add(lblCOnga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jPanelTamaño.setBackground(new java.awt.Color(204, 255, 204));

        buttonGroupTamaño.add(rbtnTam0762);
        rbtnTam0762.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnTam0762.setText("0.762");

        buttonGroupTamaño.add(rbtnTam07112);
        rbtnTam07112.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnTam07112.setText("0.7112");

        javax.swing.GroupLayout jPanelTamañoLayout = new javax.swing.GroupLayout(jPanelTamaño);
        jPanelTamaño.setLayout(jPanelTamañoLayout);
        jPanelTamañoLayout.setHorizontalGroup(
            jPanelTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTamañoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnTam07112, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnTam0762, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelTamañoLayout.setVerticalGroup(
            jPanelTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTamañoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(rbtnTam0762)
                .addGap(13, 13, 13)
                .addComponent(rbtnTam07112)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 190, 150));

        lblTamaño.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTamaño.setText("TAMAÑO (m)");
        getContentPane().add(lblTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        lblMaterial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMaterial.setText("MATERIAL");
        getContentPane().add(lblMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, 30));

        jPanelMaterial.setBackground(new java.awt.Color(204, 255, 204));

        buttonGroupMaterial.add(rbtnMatCaoba);
        rbtnMatCaoba.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnMatCaoba.setText("Caoba");

        buttonGroupMaterial.add(rbtnMatSapele);
        rbtnMatSapele.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnMatSapele.setText("Sapele");

        javax.swing.GroupLayout jPanelMaterialLayout = new javax.swing.GroupLayout(jPanelMaterial);
        jPanelMaterial.setLayout(jPanelMaterialLayout);
        jPanelMaterialLayout.setHorizontalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnMatSapele)
                    .addComponent(rbtnMatCaoba))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanelMaterialLayout.setVerticalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnMatCaoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnMatSapele)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 190, 60));

        lblCOnga1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Congas/conga3.png"))); // NOI18N
        getContentPane().add(lblCOnga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        lblSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sonido.png"))); // NOI18N
        getContentPane().add(lblSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, -1, -1));

        btnSonido.setBackground(new java.awt.Color(255, 204, 204));
        btnSonido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSonido.setText("SONIDO");
        btnSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, 30));

        jPanelPeso.setBackground(new java.awt.Color(204, 255, 204));

        buttonGroupPeso.add(rbtnPeso145);
        rbtnPeso145.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnPeso145.setText("14.5");

        buttonGroupPeso.add(rbtnPeso1616);
        rbtnPeso1616.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnPeso1616.setText("16.16");

        javax.swing.GroupLayout jPanelPesoLayout = new javax.swing.GroupLayout(jPanelPeso);
        jPanelPeso.setLayout(jPanelPesoLayout);
        jPanelPesoLayout.setHorizontalGroup(
            jPanelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnPeso1616, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnPeso145, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelPesoLayout.setVerticalGroup(
            jPanelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(rbtnPeso145)
                .addGap(15, 15, 15)
                .addComponent(rbtnPeso1616)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 170, 150));

        lblPeso.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPeso.setText("PESO (kg)");
        getContentPane().add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, 20));

        btnComprar.setBackground(new java.awt.Color(153, 255, 204));
        btnComprar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, 40));

        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/Fondo1.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasCuerdasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCuerdasActionPerformed
        // TODO add your handling code here:
        GUI_Congas menuCongas = new GUI_Congas();
        menuCongas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasCuerdasActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        GUI_Compra compra = new GUI_Compra();
        compra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonidoActionPerformed
        // TODO add your handling code here:
        
        new PercusionMembranofos().producirSonido(GUI_Congas.ins);
    }//GEN-LAST:event_btnSonidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesConga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesConga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesConga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesConga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_OpcionesConga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCuerdas;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnSonido;
    private javax.swing.ButtonGroup buttonGroupColor;
    private javax.swing.ButtonGroup buttonGroupMarca;
    private javax.swing.ButtonGroup buttonGroupMaterial;
    private javax.swing.ButtonGroup buttonGroupPeso;
    private javax.swing.ButtonGroup buttonGroupTamaño;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JPanel jPanelMarca;
    private javax.swing.JPanel jPanelMaterial;
    private javax.swing.JPanel jPanelPeso;
    private javax.swing.JPanel jPanelTamaño;
    private javax.swing.JLabel lblCOnga;
    private javax.swing.JLabel lblCOnga1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoPrincipalMarca;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSonido;
    private javax.swing.JLabel lblTamaño;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnAzul;
    private javax.swing.JRadioButton rbtnCafe;
    private javax.swing.JRadioButton rbtnCameMusic;
    private javax.swing.JRadioButton rbtnLatinPercussion;
    private javax.swing.JRadioButton rbtnMatCaoba;
    private javax.swing.JRadioButton rbtnMatSapele;
    private javax.swing.JRadioButton rbtnNegro;
    private javax.swing.JRadioButton rbtnPeso145;
    private javax.swing.JRadioButton rbtnPeso1616;
    private javax.swing.JRadioButton rbtnRojo;
    private javax.swing.JRadioButton rbtnStrong;
    private javax.swing.JRadioButton rbtnTam07112;
    private javax.swing.JRadioButton rbtnTam0762;
    // End of variables declaration//GEN-END:variables
}
