/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_Viento extends javax.swing.JFrame {

    /**
     * Creates new form Viento
     */
    public GUI_Viento() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuPrincipal = new javax.swing.JButton();
        lblTrompetas = new javax.swing.JLabel();
        btnTrompetas = new javax.swing.JButton();
        lblSaxofon = new javax.swing.JLabel();
        btnSaxofon = new javax.swing.JButton();
        lblFlauta = new javax.swing.JLabel();
        btnFlauta = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblLogoPrincipalMarca = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        lblLogoPrincipalMarca1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuPrincipal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMenuPrincipal.setText("Atrás");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 409, 90, 40));

        lblTrompetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Trompetas/tropeta1.png"))); // NOI18N
        getContentPane().add(lblTrompetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnTrompetas.setBackground(new java.awt.Color(255, 255, 255));
        btnTrompetas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTrompetas.setText("Trompetas");
        btnTrompetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrompetasActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrompetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 150, 40));

        lblSaxofon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Saxofon/saxofon1.png"))); // NOI18N
        getContentPane().add(lblSaxofon, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        btnSaxofon.setBackground(new java.awt.Color(255, 255, 255));
        btnSaxofon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSaxofon.setText("Saxofones");
        btnSaxofon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaxofonActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaxofon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 150, 40));

        lblFlauta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flautas/flauta.png"))); // NOI18N
        getContentPane().add(lblFlauta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 30, -1));

        btnFlauta.setBackground(new java.awt.Color(255, 255, 255));
        btnFlauta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnFlauta.setText("Flauntas");
        btnFlauta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlautaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlauta, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 150, 40));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("¡NUESTROS PRODUCTOS SON!");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        lblLogoPrincipalMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPrincipalMarca1.png"))); // NOI18N
        getContentPane().add(lblLogoPrincipalMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 170, 50));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/FondoDescuentos.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        lblLogoPrincipalMarca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPrincipalMarca1.png"))); // NOI18N
        getContentPane().add(lblLogoPrincipalMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        GUI_Proyecto  menuPrincipal = new GUI_Proyecto();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnTrompetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrompetasActionPerformed
        // TODO add your handling code here:
        GUI_Trompeta trompetas = new GUI_Trompeta();
        trompetas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTrompetasActionPerformed

    private void btnSaxofonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaxofonActionPerformed
        // TODO add your handling code here:
        GUI_Saxofon saxofones = new GUI_Saxofon();
        saxofones.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSaxofonActionPerformed

    private void btnFlautaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlautaActionPerformed
        // TODO add your handling code here:
        GUI_Flauta flautas = new GUI_Flauta();
        flautas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFlautaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Viento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Viento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Viento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Viento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Viento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlauta;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnSaxofon;
    private javax.swing.JButton btnTrompetas;
    private javax.swing.JLabel lblFlauta;
    private javax.swing.JLabel lblLogoPrincipalMarca;
    private javax.swing.JLabel lblLogoPrincipalMarca1;
    private javax.swing.JLabel lblSaxofon;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTrompetas;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
