/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_OpcionesGuitarraElectrica extends javax.swing.JFrame {
    public TiendaInstrumento musicGo=new TiendaInstrumento();
    /**
     * Creates new form GUI_OpcionesGuitarraElectrica
     */
    public GUI_OpcionesGuitarraElectrica() {
        initComponents();
        setLocationRelativeTo(null);
        Instrumento.nomInstrumento = "Guitarra Eléctrica";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColor = new javax.swing.ButtonGroup();
        buttonGroupMarca = new javax.swing.ButtonGroup();
        buttonGroupMaterial = new javax.swing.ButtonGroup();
        buttonGroupTamaño = new javax.swing.ButtonGroup();
        buttonGroupPeso = new javax.swing.ButtonGroup();
        lblLogoPrincipalMarca = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();
        rbtnAzul = new javax.swing.JRadioButton();
        rbtnRojo = new javax.swing.JRadioButton();
        rbtnBlanco = new javax.swing.JRadioButton();
        rbtnNegro = new javax.swing.JRadioButton();
        jPanelMarca = new javax.swing.JPanel();
        rbtnSchacter = new javax.swing.JRadioButton();
        rbtnVintage = new javax.swing.JRadioButton();
        rbtnEncore = new javax.swing.JRadioButton();
        lblMarca = new javax.swing.JLabel();
        btnAtrasCuerdas = new javax.swing.JButton();
        lblTamaño = new javax.swing.JLabel();
        jPanelTamaño = new javax.swing.JPanel();
        rbtnTam015 = new javax.swing.JRadioButton();
        rbtnTam0125 = new javax.swing.JRadioButton();
        rbtnTam014 = new javax.swing.JRadioButton();
        rbtn013 = new javax.swing.JRadioButton();
        jPanelMaterial = new javax.swing.JPanel();
        rbtnMatCaoba = new javax.swing.JRadioButton();
        rbtnMatArceDuro = new javax.swing.JRadioButton();
        lblMaterial = new javax.swing.JLabel();
        lblGuitarraAcustica1 = new javax.swing.JLabel();
        lblGuitarraAcustica = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        jPanelPeso = new javax.swing.JPanel();
        rbtnPeso115 = new javax.swing.JRadioButton();
        rbtnPeso175 = new javax.swing.JRadioButton();
        rbtnPeso160 = new javax.swing.JRadioButton();
        rbtnPeso130 = new javax.swing.JRadioButton();
        lblSonido = new javax.swing.JLabel();
        btnSonido = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoPrincipalMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPrincipalMarca1.png"))); // NOI18N
        getContentPane().add(lblLogoPrincipalMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 200, 50));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("¡Elige lo que más te guste!");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblColor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblColor.setText("COLOR");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 20));

        jPanelColor.setBackground(new java.awt.Color(204, 255, 255));

        rbtnAzul.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnAzul);
        rbtnAzul.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnAzul.setText("Azul");

        rbtnRojo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnRojo);
        rbtnRojo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnRojo.setText("Rojo");

        rbtnBlanco.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnBlanco);
        rbtnBlanco.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnBlanco.setText("Blanco");

        rbtnNegro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupColor.add(rbtnNegro);
        rbtnNegro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnNegro.setText("Negro");

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnAzul)
                    .addGroup(jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbtnNegro)
                        .addComponent(rbtnBlanco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbtnRojo, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnNegro)
                .addGap(18, 18, 18)
                .addComponent(rbtnBlanco)
                .addGap(18, 18, 18)
                .addComponent(rbtnRojo)
                .addGap(18, 18, 18)
                .addComponent(rbtnAzul)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 160));

        jPanelMarca.setBackground(new java.awt.Color(204, 255, 255));

        buttonGroupMarca.add(rbtnSchacter);
        rbtnSchacter.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnSchacter.setText("SCHACTER");

        buttonGroupMarca.add(rbtnVintage);
        rbtnVintage.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnVintage.setText("VINTAGE");

        buttonGroupMarca.add(rbtnEncore);
        rbtnEncore.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnEncore.setText("ENCORE");
        rbtnEncore.setActionCommand("");

        javax.swing.GroupLayout jPanelMarcaLayout = new javax.swing.GroupLayout(jPanelMarca);
        jPanelMarca.setLayout(jPanelMarcaLayout);
        jPanelMarcaLayout.setHorizontalGroup(
            jPanelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMarcaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnEncore)
                    .addComponent(rbtnVintage)
                    .addComponent(rbtnSchacter))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanelMarcaLayout.setVerticalGroup(
            jPanelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnSchacter)
                .addGap(18, 18, 18)
                .addComponent(rbtnVintage)
                .addGap(18, 18, 18)
                .addComponent(rbtnEncore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 110));

        lblMarca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMarca.setText("MARCA");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, 30));

        btnAtrasCuerdas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAtrasCuerdas.setText("Atrás");
        btnAtrasCuerdas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCuerdasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasCuerdas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 40));

        lblTamaño.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTamaño.setText("TAMAÑO (m)");
        getContentPane().add(lblTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        jPanelTamaño.setBackground(new java.awt.Color(204, 255, 255));

        buttonGroupTamaño.add(rbtnTam015);
        rbtnTam015.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnTam015.setText("1.5");

        buttonGroupTamaño.add(rbtnTam0125);
        rbtnTam0125.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnTam0125.setText("1.25");

        buttonGroupTamaño.add(rbtnTam014);
        rbtnTam014.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnTam014.setText("1.4");

        buttonGroupTamaño.add(rbtn013);
        rbtn013.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtn013.setText("1.1");

        javax.swing.GroupLayout jPanelTamañoLayout = new javax.swing.GroupLayout(jPanelTamaño);
        jPanelTamaño.setLayout(jPanelTamañoLayout);
        jPanelTamañoLayout.setHorizontalGroup(
            jPanelTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTamañoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn013, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnTam0125, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnTam015, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnTam014, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelTamañoLayout.setVerticalGroup(
            jPanelTamañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTamañoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnTam015)
                .addGap(13, 13, 13)
                .addComponent(rbtnTam0125)
                .addGap(18, 18, 18)
                .addComponent(rbtnTam014)
                .addGap(18, 18, 18)
                .addComponent(rbtn013)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 190, 150));

        jPanelMaterial.setBackground(new java.awt.Color(204, 255, 255));

        buttonGroupMaterial.add(rbtnMatCaoba);
        rbtnMatCaoba.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnMatCaoba.setText("Caoba");

        buttonGroupMaterial.add(rbtnMatArceDuro);
        rbtnMatArceDuro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnMatArceDuro.setText("Arce Duro");

        javax.swing.GroupLayout jPanelMaterialLayout = new javax.swing.GroupLayout(jPanelMaterial);
        jPanelMaterial.setLayout(jPanelMaterialLayout);
        jPanelMaterialLayout.setHorizontalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnMatArceDuro)
                    .addComponent(rbtnMatCaoba))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanelMaterialLayout.setVerticalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnMatCaoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnMatArceDuro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 190, 60));

        lblMaterial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMaterial.setText("MATERIAL");
        getContentPane().add(lblMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, 30));

        lblGuitarraAcustica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GuitarraElectrica/guitarra-electrica4.png"))); // NOI18N
        getContentPane().add(lblGuitarraAcustica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 120, -1));

        lblGuitarraAcustica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/GuitarraElectrica/guitarraElectrica2.png"))); // NOI18N
        getContentPane().add(lblGuitarraAcustica, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        lblPeso.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPeso.setText("PESO (kg)");
        getContentPane().add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, 20));

        jPanelPeso.setBackground(new java.awt.Color(204, 255, 255));

        buttonGroupPeso.add(rbtnPeso115);
        rbtnPeso115.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnPeso115.setText("1.15");

        buttonGroupPeso.add(rbtnPeso175);
        rbtnPeso175.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnPeso175.setText("1.75");

        buttonGroupPeso.add(rbtnPeso160);
        rbtnPeso160.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnPeso160.setText("1.60");

        buttonGroupPeso.add(rbtnPeso130);
        rbtnPeso130.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbtnPeso130.setText("1.30");

        javax.swing.GroupLayout jPanelPesoLayout = new javax.swing.GroupLayout(jPanelPeso);
        jPanelPeso.setLayout(jPanelPesoLayout);
        jPanelPesoLayout.setHorizontalGroup(
            jPanelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnPeso130, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnPeso160, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnPeso175, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnPeso115, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelPesoLayout.setVerticalGroup(
            jPanelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnPeso115)
                .addGap(15, 15, 15)
                .addComponent(rbtnPeso175)
                .addGap(18, 18, 18)
                .addComponent(rbtnPeso160)
                .addGap(18, 18, 18)
                .addComponent(rbtnPeso130)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 170, 150));

        lblSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sonido.png"))); // NOI18N
        getContentPane().add(lblSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, -1, -1));

        btnSonido.setBackground(new java.awt.Color(255, 204, 204));
        btnSonido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSonido.setText("SONIDO");
        btnSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, 30));

        btnComprar.setBackground(new java.awt.Color(153, 255, 204));
        btnComprar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, 40));

        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/Fondo1.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasCuerdasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCuerdasActionPerformed
        // TODO add your handling code here:
        GUI_GuitarraElectrica menuGuitarrasElectricas = new GUI_GuitarraElectrica();
        menuGuitarrasElectricas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasCuerdasActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        String materialInstrumento="";
        String marca="";
        String color="";
        double peso=0;
        double tamaño=0;
        
        //Material 
        if(rbtnMatCaoba.isSelected()){
        materialInstrumento = rbtnMatCaoba.getText();
        }else if(rbtnMatArceDuro.isSelected()){
            materialInstrumento = rbtnMatArceDuro.getText();
        }
        
        //Marca 
        if(rbtnVintage.isSelected()){
            marca = rbtnVintage.getText();
        }else if(rbtnEncore.isSelected()){
            marca = rbtnEncore.getText();
        }else if(rbtnSchacter.isSelected()){
            marca = rbtnSchacter.getText();
        }
        
        //Color 
        if(rbtnBlanco.isSelected()){
            color=rbtnBlanco.getText();
        }
        else if(rbtnAzul.isSelected()){
            color=rbtnAzul.getText();
        }
        else if(rbtnNegro.isSelected()){
            color=rbtnNegro.getText();
        }
        else if(rbtnRojo.isSelected()){
            color=rbtnRojo.getText();
        }
        //Tamaño 
        if(rbtn013.isSelected()){
            tamaño = Double.parseDouble(rbtn013.getText());
        }
        else if(rbtnTam0125.isSelected()){
            tamaño = Double.parseDouble(rbtnTam0125.getText());
        }
        else if(rbtnTam014.isSelected()){
            tamaño = Double.parseDouble(rbtnTam014.getText());
        }
        else if(rbtnTam015.isSelected()){
            tamaño = Double.parseDouble(rbtnTam015.getText());
        }
        
        //Peso 
        if(rbtnPeso115.isSelected()){
            peso=Double.parseDouble(rbtnPeso115.getText());
        }
        else if(rbtnPeso130.isSelected()){
            peso=Double.parseDouble(rbtnPeso130.getText());
            }
        else if(rbtnPeso160.isSelected()){
            peso=Double.parseDouble(rbtnPeso130.getText());
            }
        else if(rbtnPeso175.isSelected()){
            peso=Double.parseDouble(rbtnPeso175.getText());
            }
        
        Instrumento miGuitarraElectrica = new Electromecanicos(materialInstrumento, color, tamaño, peso, marca);
        Instrumento.precioInst = miGuitarraElectrica.calcularPrecio(Instrumento.nomInstrumento);
        musicGo.setInstrumentos(miGuitarraElectrica);
        Instrumento.descripcionInstr = miGuitarraElectrica.toString();
        
        
        GUI_Compra compra = new GUI_Compra();
        compra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonidoActionPerformed
        // TODO add your handling code here:
        
        new Electromecanicos().producirSonido(GUI_GuitarraElectrica.ins);
    }//GEN-LAST:event_btnSonidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesGuitarraElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesGuitarraElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesGuitarraElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_OpcionesGuitarraElectrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_OpcionesGuitarraElectrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCuerdas;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnSonido;
    private javax.swing.ButtonGroup buttonGroupColor;
    private javax.swing.ButtonGroup buttonGroupMarca;
    private javax.swing.ButtonGroup buttonGroupMaterial;
    private javax.swing.ButtonGroup buttonGroupPeso;
    private javax.swing.ButtonGroup buttonGroupTamaño;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JPanel jPanelMarca;
    private javax.swing.JPanel jPanelMaterial;
    private javax.swing.JPanel jPanelPeso;
    private javax.swing.JPanel jPanelTamaño;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGuitarraAcustica;
    private javax.swing.JLabel lblGuitarraAcustica1;
    private javax.swing.JLabel lblLogoPrincipalMarca;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSonido;
    private javax.swing.JLabel lblTamaño;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtn013;
    private javax.swing.JRadioButton rbtnAzul;
    private javax.swing.JRadioButton rbtnBlanco;
    private javax.swing.JRadioButton rbtnEncore;
    private javax.swing.JRadioButton rbtnMatArceDuro;
    private javax.swing.JRadioButton rbtnMatCaoba;
    private javax.swing.JRadioButton rbtnNegro;
    private javax.swing.JRadioButton rbtnPeso115;
    private javax.swing.JRadioButton rbtnPeso130;
    private javax.swing.JRadioButton rbtnPeso160;
    private javax.swing.JRadioButton rbtnPeso175;
    private javax.swing.JRadioButton rbtnRojo;
    private javax.swing.JRadioButton rbtnSchacter;
    private javax.swing.JRadioButton rbtnTam0125;
    private javax.swing.JRadioButton rbtnTam014;
    private javax.swing.JRadioButton rbtnTam015;
    private javax.swing.JRadioButton rbtnVintage;
    // End of variables declaration//GEN-END:variables
}
