/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tim
 */
public class GUI_Flauta extends javax.swing.JFrame {

    
    static String ins;
    /**
     * Creates new form Flauta
     */
    public GUI_Flauta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFlauta1 = new javax.swing.JLabel();
        lblFlauta2 = new javax.swing.JLabel();
        lblFlauta3 = new javax.swing.JLabel();
        lblFlauta4 = new javax.swing.JLabel();
        btnAtrasViento = new javax.swing.JButton();
        btnComprarFlauta1 = new javax.swing.JButton();
        btnComprarFlauta2 = new javax.swing.JButton();
        btnComprarFlauta3 = new javax.swing.JButton();
        btnComprarFlauta4 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFlauta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flautas/flauta1.png"))); // NOI18N
        getContentPane().add(lblFlauta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, -1));

        lblFlauta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flautas/flauta2.png"))); // NOI18N
        getContentPane().add(lblFlauta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 60, -1));

        lblFlauta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flautas/flauta3.png"))); // NOI18N
        getContentPane().add(lblFlauta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 80, -1));

        lblFlauta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flautas/flauta4.png"))); // NOI18N
        getContentPane().add(lblFlauta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 30, -1));

        btnAtrasViento.setBackground(new java.awt.Color(255, 255, 255));
        btnAtrasViento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAtrasViento.setText("Atrás");
        btnAtrasViento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasViento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 90, 40));

        btnComprarFlauta1.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarFlauta1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarFlauta1.setText("Comprar");
        btnComprarFlauta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarFlauta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarFlauta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 110, 30));

        btnComprarFlauta2.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarFlauta2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarFlauta2.setText("Comprar");
        btnComprarFlauta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarFlauta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarFlauta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 110, 30));

        btnComprarFlauta3.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarFlauta3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarFlauta3.setText("Comprar");
        btnComprarFlauta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarFlauta3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarFlauta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 110, 30));

        btnComprarFlauta4.setBackground(new java.awt.Color(255, 255, 255));
        btnComprarFlauta4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnComprarFlauta4.setText("Comprar");
        btnComprarFlauta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarFlauta4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprarFlauta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 110, 30));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitulo.setText("FLAUTAS");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        lblInfo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblInfo.setText("Haz click en \"comprar\" para más información!");
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 400, 40));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFondos/FondoNuevosProductos.png"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasVientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVientoActionPerformed
        // TODO add your handling code here:
        GUI_Viento intrumentoViento = new GUI_Viento();
        intrumentoViento.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasVientoActionPerformed

    private void btnComprarFlauta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarFlauta1ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesFlauta opcionesCompra = new GUI_OpcionesFlauta();
        opcionesCompra.setVisible(true);
        dispose();
        ins = "flauta1";
    }//GEN-LAST:event_btnComprarFlauta1ActionPerformed

    private void btnComprarFlauta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarFlauta2ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesFlauta opcionesCompra = new GUI_OpcionesFlauta();
        opcionesCompra.setVisible(true);
        dispose();
        ins = "flauta2";
    }//GEN-LAST:event_btnComprarFlauta2ActionPerformed

    private void btnComprarFlauta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarFlauta3ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesFlauta opcionesCompra = new GUI_OpcionesFlauta();
        opcionesCompra.setVisible(true);
        dispose();
        ins = "flauta3";
    }//GEN-LAST:event_btnComprarFlauta3ActionPerformed

    private void btnComprarFlauta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarFlauta4ActionPerformed
        // TODO add your handling code here:
        GUI_OpcionesFlauta opcionesCompra = new GUI_OpcionesFlauta();
        opcionesCompra.setVisible(true);
        dispose();
        ins = "flauta4";
    }//GEN-LAST:event_btnComprarFlauta4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Flauta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Flauta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Flauta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Flauta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Flauta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasViento;
    private javax.swing.JButton btnComprarFlauta1;
    private javax.swing.JButton btnComprarFlauta2;
    private javax.swing.JButton btnComprarFlauta3;
    private javax.swing.JButton btnComprarFlauta4;
    private javax.swing.JLabel lblFlauta1;
    private javax.swing.JLabel lblFlauta2;
    private javax.swing.JLabel lblFlauta3;
    private javax.swing.JLabel lblFlauta4;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
